config/routes.rb
Rails.application.routes.draw do
  # root to: 'results#index'
  root  'results#index'
  resources :kifus, only: [:new, :create, :edit, :update, :show, :destroy]
  get 'results/:id', to: 'results#win_or_lose'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gote.rb
class Gote < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--' },
    { id: 2,  name: 'すぎうら' },
    { id: 3,  name: 'ぷく' },
    { id: 4,  name: 'ほっしー' },
    { id: 5,  name: 'あつと' },
    { id: 6,  name: 'しゅん' },
    { id: 7,  name: 'しゅうまい' },
    { id: 8, name: 'れおす' },
    { id: 9, name: 'カイト' },
    { id: 10, name: 'へいや' },
    { id: 11, name: 'ちょうの' },
    { id: 12, name: 'きふわるべ' },
    { id: 13, name: 'たいちた' }
  ]
end

app/models/kifu.rb
class Kifu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :sente
  belongs_to_active_hash :gote
  belongs_to_active_hash :kifu_result

  with_options presence: true do
    validates :date
    validates :sente_id, numericality: { other_than:1 }
    validates :gote_id, numericality: { other_than: 1 }
    validates :result_id, numericality: { other_than: 1 }
    validates :kifu
  end
end

app/models/kifu_result.rb
class KifuResult < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '先手勝ち' },
    { id: 3, name: '後手勝ち' },
    { id: 4, name: '千日手' },
    { id: 5, name: '持将棋' }
  ]
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :results
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :member
end

app/models/sente.rb
class Sente < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--' },
    { id: 2,  name: 'すぎうら' },
    { id: 3,  name: 'ぷく' },
    { id: 4,  name: 'ほっしー' },
    { id: 5,  name: 'あつと' },
    { id: 6,  name: 'しゅん' },
    { id: 7,  name: 'しゅうまい' },
    { id: 8, name: 'れおす' },
    { id: 9, name: 'カイト' },
    { id: 10, name: 'へいや' },
    { id: 11, name: 'ちょうの' },
    { id: 12, name: 'きふわるべ' },
    { id: 13, name: 'たいちた' }
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/kifus_controller.rb
class KifusController < ApplicationController
  before_action :set_kifu, only: [:edit, :update, :show, :destroy]

  def new
    @kifu = Kifu.new
  end

  def create
    @kifu = Kifu.create(kifu_params)
    if @kifu.valid?
      @kifu.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @kifu.update(kifu_params)
      redirect_to kifu_path(@kifu.id)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    if @kifu.destroy
      redirect_to root_path
    else
      redirect_to kifu_path(@kifu.id)
    end
  end

  private

  def kifu_params
    params.require(:kifu).permit(:date, :sente_id, :gote_id, :result_id, :kifu)
  end

  def set_kifu
    @kifu = Kifu.find(params[:id])
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @members = Member.all
    @kifus = Kifu.all.order('date DESC')
  end

  def win_or_lose
    resultAry = params[:id].split("_")
    result_win = Result.find(resultAry[0])
    result_lose = Result.find(resultAry[1])
    if result_win.result == "○"
      result_win.update(result: "")
      result_lose.update(result: "")
    else result_win.result == ""
      result_win.update(result: "○")
      result_lose.update(result: "●")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kifus_helper.rb
module KifusHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/kifus/edit.html.erb
<div class="new-wrapper">
  <div class="input-forms">

  <h2>＜対局情報入力＞</h2>

    <%= form_with(model: @kifu, local: true) do |f| %>

      <%# 日付 %>
      <div class="input-field">
        <%= f.label :date, '日付：' %>
        <%= raw sprintf(
                    f.date_select(
                        :date,
                        use_month_numbers: true,
                        start_year:        2015,
                        end_year:          2025,
                        default:           Date.today,
                        date_separator:    '%s'),
                    '年 ', '月 ') + '日'
        %>
      </div>

      <div class="input-field">
        <%= f.label :sente_id, '先手：' %>
        <%= f.collection_select :sente_id, Sente.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :gote_id, '後手：' %>
        <%= f.collection_select :gote_id, Gote.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :result_id, '結果：' %>
        <%= f.collection_select :result_id, KifuResult.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :kifu, '棋譜' %><br>
        <%= f.text_area :kifu, placeholder: '棋譜を貼り付け', size: "40x10"  %>
      </div>

      <div class="submit">
        <%= f.submit "変更", class: 'submit-btn' %>
      </div>

      <div class="back">
        <%= link_to "棋譜一覧へ戻る", root_path, class: "back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/kifus/new.html.erb
<div class="new-wrapper">
  <div class="input-forms">

  <h2>＜対局情報入力＞</h2>

    <%= form_with(model: @kifu, url: kifus_path, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <%# 日付 %>
      <div class="input-field">
        <%= f.label :date, '日付：' %>
        <%= raw sprintf(
                    f.date_select(
                        :date,
                        use_month_numbers: true,
                        start_year:        2015,
                        end_year:          2025,
                        default:           Date.today,
                        date_separator:    '%s'),
                    '年 ', '月 ') + '日'
        %>
      </div>

      <div class="input-field">
        <%= f.label :sente_id, '先手：' %>
        <%= f.collection_select :sente_id, Sente.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :gote_id, '後手：' %>
        <%= f.collection_select :gote_id, Gote.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :result_id, '結果：' %>
        <%= f.collection_select :result_id, KifuResult.all, :id, :name, {} %>
      </div>

      <div class="input-field">
        <%= f.label :kifu, '棋譜' %><br>
        <%= f.text_area :kifu, placeholder: '棋譜を貼り付け', size: "40x10"  %>
      </div>

      <div class="submit">
        <%= f.submit "提出", class: 'submit-btn' %>
      </div>

      <div class="back">
        <%= link_to "棋譜一覧へ戻る", root_path, class: "back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/kifus/show.html.erb
<div class="show-wrapper">

  <div class="kifu-text">
    <textarea id="fe_text" name="" rows="10" cols="40"><%= @kifu.kifu %></textarea>
    <%# <button class='my_clip_button' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button'>
      <b>コピー</b>
    </button> %>
  </div>

  <strong>※解析は棋譜をコピーしてから押してね</strong>

  <div class="btns">
    <div class="edit">
      <%= link_to "編集", edit_kifu_path(@kifu.id), method: :get, class: "edit-btn" %>
    </div>

    <div class="destroy">
      <%= link_to "削除", kifu_path(@kifu.id), method: :delete, class: "destroy-btn" %>
    </div>

    <div class="analysis">
      <%= link_to '解析', 'https://www.shogi-extend.com/adapter', class: "analysis-btn" %>
    </div>
  </div>

  <div class="back">
    <%= link_to '棋譜一覧へ戻る', root_path, class: "back-btn" %>
  </div>

</div class="div">

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>第10回しゅが研</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <h1 class="title">第10回しゅが研<span>毎週金曜日20時〜</span></h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/results/index.html.erb
<div class="main">
  <div class="league-table">
    <h2 class="league-table-title">【リーグ表】<span class="detail">※勝利のマス目をクリック 間違えたら再クリックで取消</span></h2>
    <table id="winorlose_table" border="2" bordercolor="black" style="border-collapse: collapse">
      <tr class="top-title">
        <th class="player-title">対局者</th>

        <% @members.each do |member| %>
        <td class="opponent-name"><%= member.name %></td>
        <% end %>

        <th class="win-count-title">勝</th>
        <th class="lose-count-title">負</th>
      </tr>

      <% @members.each_with_index do |member, i| %>
      <tr class="result-cells">
        <td class="self-name"><%= member.name %></td>

        <%# 12人 %>
        <td id="op_<%= i + 1 %>_1" data-id="<%= (i * 12) + 1 %>_<%= (12 * (i * 12 + 1)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 1).result %></td>
        <td id="op_<%= i + 1 %>_2" data-id="<%= (i * 12) + 2 %>_<%= (12 * (i * 12 + 2)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 2).result %></td>
        <td id="op_<%= i + 1 %>_3" data-id="<%= (i * 12) + 3 %>_<%= (12 * (i * 12 + 3)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 3).result %></td>
        <td id="op_<%= i + 1 %>_4" data-id="<%= (i * 12) + 4 %>_<%= (12 * (i * 12 + 4)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 4).result %></td>
        <td id="op_<%= i + 1 %>_5" data-id="<%= (i * 12) + 5 %>_<%= (12 * (i * 12 + 5)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 5).result %></td>
        <td id="op_<%= i + 1 %>_6" data-id="<%= (i * 12) + 6 %>_<%= (12 * (i * 12 + 6)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 6).result %></td>
        <td id="op_<%= i + 1 %>_7" data-id="<%= (i * 12) + 7 %>_<%= (12 * (i * 12 + 7)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 7).result %></td>
        <td id="op_<%= i + 1 %>_8" data-id="<%= (i * 12) + 8 %>_<%= (12 * (i * 12 + 8)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 8).result %></td>
        <td id="op_<%= i + 1 %>_9" data-id="<%= (i * 12) + 9 %>_<%= (12 * (i * 12 + 9)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 9).result %></td>
        <td id="op_<%= i + 1 %>_10" data-id="<%= (i * 12) + 10 %>_<%= (12 * (i * 12 + 10)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 10).result %></td>
        <td id="op_<%= i + 1 %>_11" data-id="<%= (i * 12) + 11 %>_<%= (12 * (i * 12 + 11)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 11).result %></td>
        <td id="op_<%= i + 1 %>_12" data-id="<%= (i * 12) + 12 %>_<%= (12 * (i * 12 + 12)) - (144 * i + (11 - i)) %>"><%= Result.find((i * 12) + 12).result %></td>

        <%# 勝敗 %>
        <td id="win_<%= i + 1 %>">0</td>
        <td id="lose_<%= i + 1 %>">0</td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="new-link">
    <%= link_to '棋譜提出ページへ', new_kifu_path %>
  </div>

  <h2>＜棋譜一覧＞</h2>

  <div class="kifu-lists">
    <% @kifus.each do |kifu| %>
      <div class="one-kifu">

        <%# 日付 %>
        <span class="date">
          <%= kifu.date %>
        </span>

        <span class="card">

          <span class="winorlose">
            <% if kifu.result_id == 2 %>
              ○
            <% elsif kifu.result_id == 3 %>
              ●
            <% end %>
            </span>

          <%# 先手 %>
          <span class="sente">
            <%= kifu.sente.name %>
          </span>

          vs

          <%# 後手 %>
          <span class="gote">
            <%= kifu.gote.name %>
          </span>

          <span class="winorlose">
            <% if kifu.result_id == 3 %>
              ○
            <% elsif kifu.result_id == 2 %>
              ●
            <% elsif kifu.result_id == 4 %>
              千
            <% elsif kifu.result_id == 5 %>
              持
            <% end %>
            </span>

        </span>

        <%# 棋譜リンク %>
        <span class="kifu-page">
          <%= link_to '棋譜を見る', kifu_path(kifu.id)  %>
        </span>

      </div>
    <% end %>
  </div>

  <div class="member-list">
    <h2 class="member-list-title">【対局者紹介】</h2>
    <table border="2" bordercolor="black" style="border-collapse: collapse" class="member-table">

      <tr class="member-info">
        <th class="member-title">対局者</th>
        <th class="account-title">アカウント</th>
        <th class="achievement-title">実績</th>
      </tr>

      <% @members.each do |member| %>
      <tr class="member-introduction">
        <td class="member"><%= member.name %></td>
        <td class="account"><%= member.account %></td>
        <td class="achievement"><%= member.achievement %></td>
      </tr>
      <% end %>

    </table>
    </div>
  </div>
</div>